# -- enums 패키지에 있는 ActivityTime 데이터 삽입
# INSERT INTO activity_time (name) VALUES
#                                      ('WEEKDAY_MORNING'),
#                                      ('WEEKDAY_AFTERNOON'),
#                                      ('WEEKDAY_EVENING'),
#                                      ('WEEKEND_MORNING'),
#                                      ('WEEKEND_AFTERNOON'),
#                                      ('WEEKEND_EVENING');
#
# -- enums 패키지에 있는 ActivityType 데이터 삽입
# INSERT INTO activity_type (name) VALUES
#                                      ('ONLINE'),
#                                      ('OFFLINE'),
#                                      ('ALL');
#
# -- enums 패키지에 있는 Interest 데이터 삽입
# INSERT INTO interest (name) VALUES
#                                 ('WEB_DEV'),
#                                 ('APP_DEV'),
#                                 ('DESIGN_UX_UI'),
#                                 ('DESIGN_GRAPHIC'),
#                                 ('EDUCATION_MATH'),
#                                 ('EDUCATION_ENGLISH'),
#                                 ('MUSIC_PIANO'),
#                                 ('FITNESS_YOGA');
#
# -- enums 패키지에 있는 Role 데이터 삽입
# INSERT INTO role (name) VALUES
#                             ('ROLE_TEMP'),
#                             ('ROLE_MENTOR'),
#                             ('ROLE_MENTEE');
#
#
# -- Area 테이블 데이터 삽입
# INSERT INTO area (areacode, area_name) VALUES
#                                            (1, '서울'),
#                                            (2, '경기'),
#                                            (3, '인천'),
#                                            (4, '강원'),
#                                            (5, '대전');
#
# -- Sigungu 테이블 데이터 삽입 (서울)
# INSERT INTO sigungu (areacode, sigungucode, sigunguname) VALUES
#                                                              (1, 110, '종로구'),
#                                                              (1, 140, '중구'),
#                                                              (1, 170, '용산구'),
#                                                              (1, 200, '성동구'),
#                                                              (1, 215, '광진구');
#
# -- Sigungu 테이블 데이터 삽입 (경기)
# INSERT INTO sigungu (areacode, sigungucode, sigunguname) VALUES
#                                                              (2, 110, '수원시 장안구'),
#                                                              (2, 111, '수원시 권선구'),
#                                                              (2, 112, '수원시 팔달구'),
#                                                              (2, 113, '수원시 영통구'),
#                                                              (2, 130, '성남시 수정구');
#
# -- Sigungu 테이블 데이터 삽입 (인천)
# INSERT INTO sigungu (areacode, sigungucode, sigunguname) VALUES
#                                                              (3, 110, '중구'),
#                                                              (3, 140, '동구'),
#                                                              (3, 170, '미추홀구'),
#                                                              (3, 180, '연수구'),
#                                                              (3, 200, '남동구');
#
# -- Sigungu 테이블 데이터 삽입 (강원)
# INSERT INTO sigungu (areacode, sigungucode, sigunguname) VALUES
#                                                              (4, 110, '춘천시'),
#                                                              (4, 130, '원주시'),
#                                                              (4, 150, '강릉시'),
#                                                              (4, 170, '동해시'),
#                                                              (4, 190, '태백시');
#
# -- Sigungu 테이블 데이터 삽입 (대전)
# INSERT INTO sigungu (areacode, sigungucode, sigunguname) VALUES
#                                                              (5, 110, '동구'),
#                                                              (5, 140, '중구'),
#                                                              (5, 170, '서구'),
#                                                              (5, 200, '유성구'),
#                                                              (5, 230, '대덕구');


-- User 테이블 데이터 삽입 (uuid는 임의로 생성, 데이터는 기존 CSV 파일 기반)
INSERT INTO user (UUID(), provider, provider_id, user_name_attribute, name, nickname, role, profile_image_url, account_disable, area, sigungu_code, introduction, interest, activity_time, activity_type, contact_link, match_status, profile_tag, created_at, updated_at) VALUES
                                                                                                                                                                                                                                                                                     ( 'naver', '7849509557', 'user_7849509557', '김재호', '똑똑한엔지니어585', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/women/48.jpg', false, 2, 110, 'React 중심의 프로그래밍/웹개발 멘티입니다. 함께 성장하고 배우는 시간이 되었으면 합니다.', 'WEB_DEV', 'WEEKEND_MORNING', 'OFFLINE', 'mailto:yeeun78@example.com', false, 'Vue, Node.js, 프론트엔드, HTML', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('0c50c38a-1fc4-4467-b22d-15396786eef5', 'kakao', '4239749615', 'id', '이상민', '귀여운호랑이668', 'ROLE_MENTOR', 'http://k.kakaocdn.net/dn/l46I6/btr0xMg4eLE/jr6nAGrokWaCDCvlO5MzN0/img_640x640.jpg', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('0f3ce535-1347-4adc-8893-b2f0dc8f13df', 'kakao', '6678637071', 'user_6678637071', '강현준', '도전하는프로그래머822', 'ROLE_MENTOR', 'https://randomuser.me/api/portraits/men/47.jpg', false, 3, 110, '음악/피아노를 전공하고 현업에서 7년간 일하고 있습니다. 클래식 분야에서 멘토링 해드립니다.', 'MUSIC_PIANO', 'WEEKDAY_MORNING', 'ONLINE', 'mailto:yeongmi92@example.org', false, '클래식, 피아노, 작곡', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('1529ba82-609c-4af7-a788-4ef668bd7e40', 'google', '4226098582', 'user_4226098582', '문도윤', '열정적인선생님786', 'ROLE_MENTOR', 'https://randomuser.me/api/portraits/women/46.jpg', false, 5, 110, '2년차 디자인/UX/UI 멘토로 활동 중입니다. 디자인시스템 관련 질문이나 도움이 필요하시면 연락주세요.', 'DESIGN_UX_UI', 'WEEKEND_MORNING', 'OFFLINE', 'https://discord.gg/n85041', false, '피그마, 사용자경험, UX/UI', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('260bb907-fbbe-4d81-8b42-b435c8462fc5', 'kakao', '1270712018', 'user_1270712018', '김시우', '꿈꾸는창작자703', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/men/84.jpg', false, 1, 140, '디자인/그래픽에 관심이 많은 멘티입니다. 6년 경력이 있으며, 브랜딩 분야에 전문성이 있습니다.', 'DESIGN_GRAPHIC', 'WEEKEND_MORNING', 'ONLINE', 'https://t.me/rbag_652', true, '일러스트레이션, 타이포그래피, Photoshop, 브랜딩', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('27dd8a48-1975-4bea-ad13-36556436319f', 'google', '7202800256', 'user_7202800256', '박승현', '활기찬코더995', 'ROLE_MENTOR', 'https://randomuser.me/api/portraits/men/62.jpg', false, 2, 111, '그래픽디자인 중심의 디자인/그래픽 멘토입니다. 함께 성장하고 배우는 시간이 되었으면 합니다.', 'DESIGN_GRAPHIC', 'WEEKDAY_AFTERNOON', 'ALL', 'https://open.kakao.com/o/18259g', false, 'Illustrator, Photoshop, 브랜딩, 타이포그래피, 일러스트레이션', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('31816be1-a30c-455f-9a6d-595192fff065', 'google', '7630567724', 'user_7630567724', '이현주', '즐거운선생님918', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/women/94.jpg', false, 3, 140, '교육/영어 분야에서 활동하고 있는 멘티입니다. 토플을 주로 다루고 있습니다.', 'EDUCATION_ENGLISH', 'WEEKEND_MORNING', 'ALL', 'https://open.kakao.com/o/69817g', true, '토플, 영작문, 영어교육, 영문법', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('3927212d-d4bc-4dde-9ddc-af218b3c1813', 'google', '6289540655', 'user_6289540655', '조옥자', '꿈꾸는코더474', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/women/21.jpg', false, 4, 110, '4년차 디자인/그래픽 멘티로 활동 중입니다. 일러스트레이션 관련 질문이나 도움이 필요하시면 연락주세요.', 'DESIGN_GRAPHIC', 'WEEKEND_AFTERNOON', 'ALL', 'https://discord.gg/n41220', false, '타이포그래피, 브랜딩, 그래픽디자인, Photoshop, 일러스트레이션', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('3a210a76-be9a-4575-b2ae-bd5f4ac88a6e', 'naver', '2083521291', 'user_2083521291', '배영수', '행복한선생님967', 'ROLE_MENTOR', 'https://randomuser.me/api/portraits/women/62.jpg', false, 5, 110, '디자인/그래픽를 전공하고 현업에서 10년간 일하고 있습니다. 그래픽디자인 분야에서 멘토링 해드립니다.', 'DESIGN_GRAPHIC', 'WEEKDAY_AFTERNOON', 'ALL', 'mailto:subin32@example.org', false, '타이포그래피, Illustrator, Photoshop, 일러스트레이션', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('3bafe9bc-b39b-43f3-8101-64173e02e2aa', 'google', '4141153082', 'user_4141153082', '이지은', '성장하는선생님553', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/women/56.jpg', false, 1, 170, '운동/요가 분야에서 활동하고 있는 멘티입니다. 요가강사을 주로 다루고 있습니다.', 'FITNESS_YOGA', 'WEEKEND_MORNING', 'ONLINE', 'https://discord.gg/o75791', true, '요가, 스트레칭, 요가강사', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('3d27dcd4-6c5f-41f6-a384-20bcb98415af', 'google', '6446473899', 'user_6446473899', '서경자', '활기찬디자이너501', 'ROLE_MENTOR', 'https://randomuser.me/api/portraits/men/74.jpg', false, 2, 112, '8년차 디자인/그래픽 멘토로 활동 중입니다. Photoshop 관련 질문이나 도움이 필요하시면 연락주세요.', 'DESIGN_GRAPHIC', 'WEEKDAY_EVENING', 'OFFLINE', 'https://discord.gg/a20721', false, '브랜딩, 일러스트레이션, 타이포그래피', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('43694914-e9e8-4deb-8c3d-764bf84bafd3', 'naver', '2421170358', 'user_2421170358', '이숙자', '친절한개발자229', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/women/36.jpg', false, 3, 170, '음악/피아노에 관심이 많은 멘티입니다. 8년 경력이 있으며, 작곡 분야에 전문성이 있습니다.', 'MUSIC_PIANO', 'WEEKEND_MORNING', 'ONLINE', 'mailto:sangceol45@example.net', true, '재즈, 작곡, 음악이론', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('460cf7d0-7658-4c12-b87a-5e9f1bf20eee', 'kakao', '4239436898', 'id', '김태현', '귀여운독수리923', 'ROLE_MENTEE', 'http://k.kakaocdn.net/dn/cyPYC8/btsC53q5wN3/zUE8h8M7DGLq4Oko6NXh91/img_640x640.jpg', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('4d172f51-e064-4d4b-b5d5-059c99323606', 'google', '1099543828', 'user_1099543828', '이진호', '열정적인개발자657', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/men/84.jpg', false, 4, 130, '운동/요가 분야에서 활동하고 있는 멘티입니다. 스트레칭을 주로 다루고 있습니다.', 'FITNESS_YOGA', 'WEEKEND_EVENING', 'ONLINE', 'https://open.kakao.com/o/86683d', false, '요가포즈, 필라테스, 요가, 요가강사, 명상', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('4df08109-a024-4dc8-af31-63dd0add6232', 'google', '3865243985', 'user_3865243985', '윤정숙', '활기찬코더753', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/women/68.jpg', false, 5, 230, '디자인/UX/UI 분야에서 활동하고 있는 멘티입니다. 어도비XD을 주로 다루고 있습니다.', 'DESIGN_UX_UI', 'WEEKDAY_EVENING', 'OFFLINE', 'https://open.kakao.com/o/22340z', false, '스케치, 어도비XD, 피그마, 사용자경험, 디자인시스템', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('5511f72a-efcd-419f-80e9-b23072ff8786', 'kakao', '7667396271', 'user_7667396271', '황현우', '똑똑한프로그래머355', 'ROLE_MENTOR', 'https://randomuser.me/api/portraits/men/56.jpg', false, 1, 200, '디자인/그래픽를 전공하고 현업에서 2년간 일하고 있습니다. Photoshop 분야에서 멘토링 해드립니다.', 'DESIGN_GRAPHIC', 'WEEKDAY_EVENING', 'OFFLINE', 'https://open.kakao.com/o/81910z', true, 'Photoshop, 그래픽디자인, 일러스트레이션', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('55886205-98a8-4102-9c2c-6df8c471246e', 'google', '1060042940', 'user_1060042940', '구경자', '즐거운창작자990', 'ROLE_MENTOR', 'https://randomuser.me/api/portraits/women/41.jpg', false, 2, 113, '디자인/그래픽 분야에서 활동하고 있는 멘토입니다. 타이포그래피을 주로 다루고 있습니다.', 'DESIGN_GRAPHIC', 'WEEKEND_EVENING', 'ONLINE', 'https://discord.gg/i31174', false, 'Illustrator, 타이포그래피, 일러스트레이션, 그래픽디자인, Photoshop', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('599fff14-068f-46ec-b4c0-4b8feacc3e21', 'naver', '2360756277', 'user_2360756277', '최지후', '친절한엔지니어345', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/women/69.jpg', false, 3, 180, '음악/피아노 분야에서 활동하고 있는 멘티입니다. 음악이론을 주로 다루고 있습니다.', 'MUSIC_PIANO', 'WEEKDAY_MORNING', 'OFFLINE', 'https://t.me/jinugim_543', false, '클래식, 음악이론, 피아노', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('5b80a666-c59e-47d0-b902-4b9b86b369ef', 'naver', '6128488992', 'user_6128488992', '고우진', '꿈꾸는코더851', 'ROLE_MENTOR', 'https://randomuser.me/api/portraits/women/30.jpg', false, 4, 150, 'Node.js 중심의 프로그래밍/웹개발 멘토입니다. 함께 성장하고 배우는 시간이 되었으면 합니다.', 'WEB_DEV', 'WEEKDAY_AFTERNOON', 'ALL', 'https://open.kakao.com/o/52193z', false, 'Django, 웹개발, CSS, 백엔드', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('62673e38-64da-4d78-a619-1f07ebfc45b9', 'naver', '2542912619', 'user_2542912619', '이정식', '행복한기획자304', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/men/50.jpg', false, 5, 110, '일러스트레이션 중심의 디자인/그래픽 멘티입니다. 함께 성장하고 배우는 시간이 되었으면 합니다.', 'DESIGN_GRAPHIC', 'WEEKEND_AFTERNOON', 'ONLINE', 'https://open.kakao.com/o/18207w', false, '타이포그래피, 브랜딩, Illustrator, 그래픽디자인, Photoshop', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('6c33409c-ca00-4129-8d5b-8eade714c805', 'naver', '2557107874', 'user_2557107874', '황정식', '창의적인멘토556', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/men/39.jpg', false, 1, 110, '음악/피아노를 전공하고 현업에서 9년간 일하고 있습니다. 음악이론 분야에서 멘토링 해드립니다.', 'MUSIC_PIANO', 'WEEKEND_AFTERNOON', 'ONLINE', 'mailto:siubag@example.org', false, '피아노, 클래식, 피아노교육, 재즈, 작곡', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('6d8ee79f-0bd4-43ec-af52-31806457c28b', 'google', '5660957507', 'user_5660957507', '강정숙', '똑똑한기획자113', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/men/10.jpg', false, 2, 130, '수학교육 중심의 교육/수학 멘티입니다. 함께 성장하고 배우는 시간이 되었으면 합니다.', 'EDUCATION_MATH', 'WEEKDAY_AFTERNOON', 'ONLINE', 'https://discord.gg/p11150', false, '수학문제풀이, 미적분, 통계학', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('7245d80a-36a7-4599-bf4d-874fa6487f77', 'google', '5015414717', 'user_5015414717', '손보람', '성장하는디자이너602', 'ROLE_MENTOR', 'https://randomuser.me/api/portraits/men/62.jpg', false, 3, 200, '교육/수학에 관심이 많은 멘토입니다. 7년 경력이 있으며, 통계학 분야에 전문성이 있습니다.', 'EDUCATION_MATH', 'WEEKDAY_AFTERNOON', 'OFFLINE', 'https://open.kakao.com/o/91130e', true, '수학, 수학교육, 선형대수, 미적분, 통계학', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('72af1101-3881-4f05-b008-be06f2cb4035', 'google', '4118603686', 'user_4118603686', '김옥순', '행복한멘토74', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/women/62.jpg', false, 4, 170, '10년차 프로그래밍/앱개발 멘티로 활동 중입니다. Swift 관련 질문이나 도움이 필요하시면 연락주세요.', 'APP_DEV', 'WEEKEND_AFTERNOON', 'ALL', 'https://t.me/mmin_493', true, '모바일, Flutter, Kotlin, iOS, Swift', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('76115e5e-000e-4b2e-89f0-318c9f45e1e3', 'kakao', '8886215084', 'user_8886215084', '김수빈', '성장하는코더279', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/men/29.jpg', false, 5, 230, '재즈 중심의 음악/피아노 멘티입니다. 함께 성장하고 배우는 시간이 되었으면 합니다.', 'MUSIC_PIANO', 'WEEKEND_EVENING', 'ONLINE', 'https://open.kakao.com/o/80919a', true, '작곡, 음악이론, 피아노교육, 재즈', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('7e5593c2-2a44-4cb9-ad03-8ebf6e5626d5', 'google', '3424899888', 'user_3424899888', '박지연', '창의적인코더444', 'ROLE_MENTOR', 'https://randomuser.me/api/portraits/women/79.jpg', false, 1, 110, '프로그래밍/앱개발에 관심이 많은 멘토입니다. 2년 경력이 있으며, iOS 분야에 전문성이 있습니다.', 'APP_DEV', 'WEEKEND_AFTERNOON', 'ALL', 'mailto:baggeonu@example.com', false, 'React Native, 하이브리드앱, Flutter', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('8adaf70b-9a73-4fa1-8255-1718b53b2a91', 'google', '7497296315', 'user_7497296315', '박민서', '즐거운창작자42', 'ROLE_MENTOR', 'https://randomuser.me/api/portraits/men/65.jpg', false, 2, 111, '프로그래밍/앱개발를 전공하고 현업에서 2년간 일하고 있습니다. 모바일 분야에서 멘토링 해드립니다.', 'APP_DEV', 'WEEKDAY_AFTERNOON', 'ONLINE', 'https://discord.gg/e68402', false, '앱개발, Swift, Android, Kotlin', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('8eeac781-abba-4ba8-ab33-58d694e832bd', 'kakao', '4660846158', 'user_4660846158', '이혜진', '도전하는창작자218', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/women/73.jpg', false, 3, 140, '브랜딩 중심의 디자인/그래픽 멘티입니다. 함께 성장하고 배우는 시간이 되었으면 합니다.', 'DESIGN_GRAPHIC', 'WEEKDAY_EVENING', 'ALL', 'https://t.me/jiminryu_682', false, 'Photoshop, 타이포그래피, Illustrator, 브랜딩, 그래픽디자인', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('95f380f1-9782-476e-9004-2b85c540e5bb', 'kakao', '7892575028', 'user_7892575028', '김예은', '즐거운창작자49', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/men/87.jpg', false, 4, 130, '10년차 프로그래밍/웹개발 멘티로 활동 중입니다. 풀스택 관련 질문이나 도움이 필요하시면 연락주세요.', 'WEB_DEV', 'WEEKDAY_AFTERNOON', 'ALL', 'https://discord.gg/q98355', false, 'React, CSS, 백엔드, Node.js, Spring', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('984b3c36-70dd-47f6-b50c-ef0b0d0300ab', 'google', '107005140079282865117', 'sub', 'N Y', '용감한여우985', 'ROLE_MENTEE', 'https://lh3.googleusercontent.com/a/ACg8ocIpyXoJ8WP4qqHvVM_jAFaaOvlEDOAAjYSEvMLa2k1QWuIBsY8=s96-c', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('9b7a6f70-10d6-4673-8bde-c94090fa7ff6', 'naver', '9008898783', 'user_9008898783', '심지영', '귀여운펭귄386', 'ROLE_MENTOR', 'https://randomuser.me/api/portraits/women/33.jpg', false, 5, 230, 'HTML 중심의 프로그래밍/웹개발 멘토입니다. 함께 성장하고 배우는 시간이 되었으면 합니다.', 'WEB_DEV', 'WEEKDAY_EVENING', 'ONLINE', 'https://open.kakao.com/o/14211i', false, 'Node.js, Vue, 백엔드, Django', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('a82a57c5-0353-46da-87d4-492cb7771917', 'google', '107563333661764360334', 'sub', '테스트용 더미', '귀여운펭귄3861', 'ROLE_MENTOR', 'https://lh3.googleusercontent.com/a/ACg8ocIKec0K3jC-RNGGAUZONZ3KK32CU4FXVjdbaksef6eZCz8L_A=s96-c', false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('b297335a-486d-4ee6-822f-cff793116592', 'naver', '5312909050', 'user_5312909050', '조춘자', '즐거운엔지니어437', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/men/24.jpg', false, 1, 110, '프로그래밍/앱개발에 관심이 많은 멘티입니다. 6년 경력이 있으며, iOS 분야에 전문성이 있습니다.', 'APP_DEV', 'WEEKEND_EVENING', 'ONLINE', 'https://open.kakao.com/o/41704d', false, 'Android, 모바일, 하이브리드앱, Swift, 앱개발', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('b64074de-bbf9-480b-8672-b7343efb1ed0', 'naver', '9878688001', 'user_9878688001', '김수민', '창의적인기획자913', 'ROLE_MENTOR', 'https://randomuser.me/api/portraits/women/1.jpg', false, 2, 112, '7년차 디자인/UX/UI 멘토로 활동 중입니다. UX/UI 관련 질문이나 도움이 필요하시면 연락주세요.', 'DESIGN_UX_UI', 'WEEKEND_MORNING', 'ALL', 'https://discord.gg/f20598', true, '피그마, 사용자경험, UX/UI, 어도비XD, 인터랙션디자인', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('b65b02bd-4818-4872-9184-78c258c7960a', 'kakao', '7518336102', 'user_7518336102', '윤승현', '똑똑한디자이너324', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/men/2.jpg', false, 3, 180, '음악/피아노를 전공하고 현업에서 8년간 일하고 있습니다. 재즈 분야에서 멘토링 해드립니다.', 'MUSIC_PIANO', 'WEEKEND_MORNING', 'OFFLINE', 'https://discord.gg/w36992', false, '음악이론, 피아노교육, 작곡, 피아노', NOW(), NOW()),
                                                                                                                                                                                                                                                                                     ('b712512d-acc1-4a82-85fa-9aee0390871b', 'kakao', '2287501839', 'user_2287501839', '이미경', '똑똑한창작자433', 'ROLE_MENTEE', 'https://randomuser.me/api/portraits/women/87.jpg', false, 4, 150, '교육/수학를 전공하고 현업에서 1년간 일하고 있습니다. 통계학 분야에서 멘토링 해드립니다.', 'EDUCATION_MATH', 'WEEKEND_MORNING', 'ONLINE', 'https://discord.gg/r94834', false, '수학교육, 선형대수, 수학', NOW(), NOW());
